# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: CmdLine@2
  inputs:
    script: |
      npm install
      npm install -g @angular/cli
  displayName: 'Install dependencies'

- task: CmdLine@2
  inputs:
    script: |
      ng test --watch=false
      ng e2e
    failOnStderr: true
  displayName: 'Run tests'

- task: CmdLine@2
  inputs:
    script: 'ng build --prod'

- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'powersrvr connection'
    sourceFolder: 'dist/minesweeper'
    contents: '**'
    targetFolder: '/var/www/minesweeper'
    cleanTargetFolder: true
    failOnEmptySource: true
  displayName: 'Copy to server'
